#ifndef KINOVALIB_OPENAPI_GLOBAL_H
#define KINOVALIB_OPENAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KINOVALIB_OPENAPI_LIBRARY)
#  define KINOVALIB_OPENAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define KINOVALIB_OPENAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KINOVALIB_OPENAPI_GLOBAL_H
